language: perl
perl:
  - "5.20"
  - "5.16"
  - "5.10"
env:
  - "MOJO_ASSETPACK_DEBUG=1 TEST_POD=1"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage IO::Socket::SSL"
  - "cpanm -n https://github.com/jhthorsen/mojolicious-plugin-assetpack/archive/master.tar.gz"
  - "cpanm -n --installdeps ."
script: "perl Makefile.PL && make test TEST_VERBOSE=1"
notifications:
  email: false
